name: fin_enlight
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  webview_flutter: 4.4.0
  ogp_data_extract: ^0.2.1

  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.4
  drift: ^2.19.1+1
  drift_dev: ^2.26.0
  sqlite3_flutter_libs: ^0.5.0

  provider: ^6.1.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  meta: ^1.15.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  equatable: ^2.0.7
  intl: ^0.19.0
  flutter_multi_formatter: ^2.13.0

  auto_route: ^9.3.0+1
  collection: ^1.19.0
  permission_handler: ^11.4.0
  flutter_udid: ^4.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.1

  flutter_launcher_icons: ^0.14.3

  freezed: ^3.0.6
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

  auto_route_generator: ^9.3.1

flutter:
  uses-material-design: true
